spring.application.name=schoolDev
spring.datasource.url=jdbc:postgresql://10.0.0.4:5432/schoolDevDatabase
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

springdoc.swagger-ui.url=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true

app.jwt.secret-key=592452482369813652395236658961456325655248566695168215689512757766931
app.jwt.expiration=96000000