spring.application.name=schoolDev
spring.datasource.url=jdbc:postgresql://localhost:5432/SchoolDev
spring.datasource.username=postgres
spring.datasource.password=Saxomat+15
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true