spring.application.name=schoolDev
spring.datasource.url=jdbc:postgresql://10.0.0.4:5432/schoolDevDatabase
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

springdoc.swagger-ui.url=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true

app.secret-key=59245248236981365239523665
app.jwt-expiration=960000 # 24 hours in milliseconds